<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;

class MakeValidator extends GeneratorCommand
{

    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'make:validator';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new validator class extends ValidatorBaseAbstract';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Validator';


    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub()
    {
        return __DIR__.'/stubs/validator.stub';
    }

    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace .'\Validators'; // TODO: Change the autogenerated stub
    }
}
